# Generated by Django 5.2 on 2025-05-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idCotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vigencia', models.DateTimeField()),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=11)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
    ]
