# Generated by Django 5.2 on 2025-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='orden_compra',
            field=models.CharField(default='sin_codigo', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='token_webpay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
