# Generated by Django 5.2 on 2025-05-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioNeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_carrito', models.ForeignKey(blank=True, db_column='id_carrito', null=True, on_delete=django.db.models.deletion.PROTECT, to='carrito.carrito')),
            ],
        ),
    ]
