# Generated by Django 5.2 on 2025-05-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_id_categoria_producto_id_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
