# Generated by Django 5.2 on 2025-06-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_precioproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
    ]
