# Generated by Django 5.2 on 2025-06-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_remove_producto_imagen_producto_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
