# Generated by Django 5.2 on 2025-06-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaTecnica', '0001_initial'),
        ('producto', '0007_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='fichaTecnica.fichatecnica'),
        ),
    ]
