# Generated by Django 5.2 on 2025-06-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_remove_producto_archivo_pdf_producto_ficha_tecnica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioProducto',
        ),
    ]
