# Generated by Django 5.2 on 2025-05-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleVenta', '0001_initial'),
        ('venta', '0002_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta'),
        ),
    ]
