# Generated by Django 5.2 on 2025-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_id_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='idUsuario',
        ),
    ]
