# Generated by Django 5.2.3 on 2025-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
