# Generated by Django 5.2 on 2025-06-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaTecnica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='productos/pdfs/'),
        ),
    ]
