# Generated by Django 5.2 on 2025-06-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensajeContacto',
            new_name='Contacto',
        ),
    ]
